/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const AttributeValue = sequelize.define('AttributeValue', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    attributeCategory: DataTypes.INTEGER(11),
    value: DataTypes.STRING(100),
  }, {
      tableName: 'AttributeValue',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return AttributeValue;
  };