/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const AttributeCategory = sequelize.define('AttributeCategory', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    code: DataTypes.STRING(20),
    uri: DataTypes.STRING(100),
    name: DataTypes.STRING(50),
    description: DataTypes.STRING,
    dataTypeId: DataTypes.INTEGER(11),
  }, {
      tableName: 'AttributeCategory',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return AttributeCategory;
  };