/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Authorship = sequelize.define('Authorship', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    datasetPUI: DataTypes.STRING(254),
    license: DataTypes.STRING(254),
  }, {
      tableName: 'Authorship',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Authorship.belongsTo(models.TrialAuthorship, {
            foreignKey: 'id',              //on Authorship
            targetKey: 'authorshipId',  //foreign key  
          }); 
        }
      },
    });

    return Authorship;
  };