/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const BreedingMethod = sequelize.define('BreedingMethod', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    abbreviation: DataTypes.STRING(20),
    breedingMethodName: DataTypes.STRING(100),
    description: DataTypes.STRING,
  }, {
      tableName: 'BreedingMethod',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          BreedingMethod.belongsTo(models.Germplasm, {
            foreignKey: 'id',              //on BreedingMethod
            targetKey: 'breedingMethodId',  //foreign key  
          }); 
        }
      },
    });

    return BreedingMethod;
  };