/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Calls = sequelize.define('Calls', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(254),
    path: DataTypes.STRING(50),
  }, {
      tableName: 'Calls',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Calls.belongsTo(models.DataTypes, {
            foreignKey: 'id',              //on Calls
            targetKey: 'callId',  //foreign key  
          }); 
          Calls.belongsTo(models.Methods, {
             foreignKey: 'id',  //on Methods
             targetKey: 'callId',
          });
          Calls.belongsTo(models.Versions, {
            foreignKey: 'id',              //on Calls
            targetKey: 'callId',  //foreign key  
          }); 
        }
      },
    });

    return Calls;
  };