/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Country = sequelize.define('Country', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(100),
    code: DataTypes.STRING(3),
  }, {
      tableName: 'Country',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Country.belongsTo(models.Germplasm, {
            foreignKey: 'id',              //on Country
            targetKey: 'countryOfOrigin',  //foreign key  
          }); 
        }
      },
    });

    return Country;
  };