/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Crop = sequelize.define('Crop', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    commonCropName: DataTypes.STRING(50),
  }, {
      tableName: 'Crop',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Crop.belongsTo(models.ObservationVariable, {
            foreignKey: 'id',              //on Crop
            targetKey: 'crop',  //foreign key  
          });
          Crop.belongsTo(models.Species, {
            foreignKey: 'id',              //on Crop
            targetKey: 'cropId',  //foreign key  
          }); 
        }
      },
    });

    return Crop;
  };