/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const DataLink = sequelize.define('DataLink', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    studyId: DataTypes.INTEGER(11),
    name: DataTypes.STRING(254),
    type: DataTypes.STRING(254),
    url: DataTypes.STRING(254),
  }, {
      tableName: 'DataLink',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          DataLink.belongsTo(models.Study, {
            foreignKey: 'studyId',              //on DataLink
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return DataLink;
  };