/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DTypes) {
    const DataTypes = sequelize.define('DataTypes', {
      id: { 
        type: DTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    callId: DTypes.INTEGER(11),
    dataType: DTypes.STRING(30),
  }, {
      tableName: 'DataTypes',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          DataTypes.belongsTo(models.Calls, {
            foreignKey: 'callId',              //on DataTypes
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return DataTypes;
  };