/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const DonorInstitute = sequelize.define('DonorInstitute', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    germplasmId: DataTypes.INTEGER(11),
    DonorGermplasmId: DataTypes.INTEGER(11),
    instituteId: DataTypes.INTEGER(11),
  }, {
      tableName: 'DonorInstitute',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
          DonorInstitute.belongsTo(models.Institution,{
            foreignKey: 'instituteId',
            targetKey: 'id'
          }),
          DonorInstitute.belongsTo(models.Germplasm,{
            foreignKey: 'donorGermplasmId',
            targetKey: 'id'
          }) 
        }
      },
    });

    return DonorInstitute;
  };