/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const GenomeMap = sequelize.define('GenomeMap', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(50),
    speciesId: DataTypes.INTEGER(11),
    type: DataTypes.STRING(20),
    unit: DataTypes.STRING(5),
    publishedDate: DataTypes.DATE,
    markerCount: DataTypes.INTEGER(11),
    linkageGroupCount: DataTypes.INTEGER(11),
    comments: DataTypes.STRING,
  }, {
      tableName: 'GenomeMap',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return GenomeMap;
  };