/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Germplasm = sequelize.define('Germplasm', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    speciesId: DataTypes.INTEGER(11),
    holdingInstitution: DataTypes.INTEGER(50),
    defaultDisplayName: DataTypes.STRING(50),
    accessionNumber: DataTypes.STRING(20),
    germplasmPUI: DataTypes.STRING(100),
    pedigree: DataTypes.STRING(50),
    seedSource: DataTypes.STRING(100),
    biologicalStatusOfAccessionCode: DataTypes.STRING(50),
    acquisitionDate: DataTypes.DATE,
    countryOfOrigin: DataTypes.INTEGER(11),
  }, {
      tableName: 'Germplasm',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Germplasm.belongsTo(models.StudyGermplasm,{
            foreignKey: 'id',
            targetKey: 'germplasmId'
          }) 
          Germplasm.belongsTo(models.Species, {
            foreignKey: 'speciesId',
          });
          Germplasm.belongsTo(models.GermplasmStorage, {
            foreignKey: 'id',
            targetKey: 'germplasmId',
          });
          Germplasm.belongsTo(models.Institution, {
            foreignKey: 'holdingInstitution',
          });
          Germplasm.belongsTo(models.Country, {
            foreignKey: 'countryOfOrigin',
          });
//          Germplasm.belongsToMany(models.Crop,{
//            through: models.Species,
//            foreignKey: 'id',     //on the species
//          })
          Germplasm.belongsTo(models.GermplasmSynonym,{
            foreignKey: 'id',     //on Germplasm
            targetKey: 'germplasmId',
          })
          Germplasm.belongsTo(models.GermplasmParents,{
            foreignKey: 'id',     //on Germplasm
            targetKey: 'childId',
          })
          Germplasm.belongsTo(models.DonorInstitute,{
            foreignKey: 'id',
            targetKey: 'germplasmId',
          })

        }
      },
    });

    return Germplasm;
  };