/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Germplasm = sequelize.define('Germplasm', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    speciesId: DataTypes.INTEGER(11),
    holdingInstitution: DataTypes.INTEGER(50),
    defaultDisplayName: DataTypes.STRING(50),
    accessionNumber: DataTypes.STRING(20),
    germplasmPUI: DataTypes.STRING(100),
    pedigree: DataTypes.STRING(50),
    seedSource: DataTypes.STRING(100),
    biologicalStatusOfAccessionCode: DataTypes.STRING(50),
    acquisitionDate: DataTypes.DATE,
    countryOfOrigin: DataTypes.INTEGER(11),
    breedingMethodId: DataTypes.INTEGER(11),
  }, {
      tableName: 'Germplasm',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Germplasm.belongsTo(models.DonorInstitute, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'germplasmId',  //foreign key  
          });
          Germplasm.belongsTo(models.Species, {
            foreignKey: 'speciesId',              //on Germplasm
            targetKey: 'id',  //foreign key  
          });
          Germplasm.belongsTo(models.Institution, {
            foreignKey: 'holdingInstitution',              //on Germplasm
            targetKey: 'id',  //foreign key  
          });
          Germplasm.belongsTo(models.Country, {
            foreignKey: 'countryOfOrigin',              //on Germplasm
            targetKey: 'id',  //foreign key  
          });
          Germplasm.belongsTo(models.BreedingMethod, {
            foreignKey: 'breedingMethodId',              //on Germplasm
            targetKey: 'id',  //foreign key  
          });
          Germplasm.belongsTo(models.GermplasmParents, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'parent1Id',  //foreign key  
          });
          Germplasm.belongsTo(models.GermplasmParents, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'parent2Id',  //foreign key  
          });
          Germplasm.belongsTo(models.GermplasmParents, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'childId',  //foreign key  
          });
          Germplasm.belongsTo(models.StudyGermplasm, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'germplasmId',  //foreign key  
          }); 
          Germplasm.belongsTo(models.GermplasmStorage, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'germplasmId',  //foreign key  
          }); 
          Germplasm.belongsTo(models.GermplasmSynonym, {
            foreignKey: 'id',              //on Germplasm
            targetKey: 'germplasmId',  //foreign key  
          }); 
        }
      },
    });

    return Germplasm;
  };