/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const LinkageGroup = sequelize.define('LinkageGroup', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    genomeMapId: DataTypes.INTEGER(11),
    numberMarkers: DataTypes.INTEGER(11),
    maxPosition: DataTypes.INTEGER(11),
  }, {
      tableName: 'LinkageGroup',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return LinkageGroup;
  };