/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const LocationAdditionalInfo = sequelize.define('LocationAdditionalInfo', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    location: DataTypes.INTEGER(11),
    propertyName: DataTypes.STRING(50),
    propertyValue: DataTypes.STRING(100),
  }, {
      tableName: 'LocationAdditionalInfo',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          LocationAdditionalInfo.belongsTo(models.Location, {
            foreignKey: 'location',              //on LocationAdditionalInfo
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return LocationAdditionalInfo;
  };