/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const MarkerprofileValue = sequelize.define('MarkerprofileValue', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    markerprofileId: DataTypes.INTEGER(11),
    markervalue1Id: DataTypes.INTEGER(11),
    markervalue2Id: DataTypes.INTEGER(11),
  }, {
      tableName: 'MarkerprofileValue',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return MarkerprofileValue;
  };