/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Marker = sequelize.define('Marker', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(50),
    linkageGroupId: DataTypes.INTEGER(11),
    type: DataTypes.STRING(20),
    location: DataTypes.INTEGER(11),
  }, {
      tableName: 'Marker',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Marker.belongsTo(models.MarkerAnalysisMethods, {
            foreignKey: 'id',              //on Marker
            targetKey: 'markerId',  //foreign key  
          }); 
        }
      },
    });

    return Marker;
  };