/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const MarkerAnalysisMethods = sequelize.define('MarkerAnalysisMethods', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    markerId: DataTypes.INTEGER(11),
    analysisMethod: DataTypes.STRING(50),
  }, {
      tableName: 'MarkerAnalysisMethods',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          MarkerAnalysisMethods.belongsTo(models.Marker, {
            foreignKey: 'markerId',              //on MarkerAnalysisMethods
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return MarkerAnalysisMethods;
  };