/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const MarkerSynonym = sequelize.define('MarkerSynonym', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    markerId: DataTypes.INTEGER(11),
    synonym: DataTypes.STRING(50),
  }, {
      tableName: 'MarkerSynonym',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return MarkerSynonym;
  };