/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const ObservationUnitXRef = sequelize.define('ObservationUnitXRef', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    observationUnitId: DataTypes.INTEGER(11),
    source: DataTypes.STRING(255),
    xref: DataTypes.STRING(255),
  }, {
    tableName: 'ObservationUnitXRef',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        ObservationUnitXRef.belongsTo(models.ObservationUnit, {
          foreignKey: 'observationUnitId',              //on ObservationUnitXRef
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return ObservationUnitXRef;
};
