/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const ObservationUnit = sequelize.define('ObservationUnit', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(100),
    level: DataTypes.STRING(12),
    studyId: DataTypes.INTEGER(11),
    plantId: DataTypes.INTEGER(11),
    plotId: DataTypes.INTEGER(11),
    sampleId: DataTypes.INTEGER(11),
  }, {
      tableName: 'ObservationUnit',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
          ObservationUnit.belongsTo(models.Sample, {
            foreignKey: 'sampleId',              //on ObservationUnit
            targetKey: 'id',  //foreign key  
          });   
          ObservationUnit.belongsTo(models.Plant, {
            foreignKey: 'plantId',              //on ObservationUnit
            targetKey: 'id',  //foreign key  
          });
          ObservationUnit.belongsTo(models.Plot, {
            foreignKey: 'plotId',              //on ObservationUnit
            targetKey: 'id',  //foreign key  
          });
          ObservationUnit.belongsTo(models.Study, {
            foreignKey: 'studyId',              //on ObservationUnit
            targetKey: 'id',  //foreign key  
          });
          ObservationUnit.belongsTo(models.ObservationUnitXRef, {
            foreignKey: 'id',              //on ObservationUnit
            targetKey: 'observationUnitId',  //foreign key  
          });

        }
      },
    });

    return ObservationUnit;
  };