/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const ObservationVariableSynonym = sequelize.define('ObservationVariableSynonym', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    observationVariableId: DataTypes.INTEGER(11),
    synonym: DataTypes.STRING(200),
  }, {
      tableName: 'ObservationVariableSynonym',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          ObservationVariableSynonym.belongsTo(models.ObservationVariable, {
            foreignKey: 'observationVariableId',              //on ObservationVariableSynonym
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return ObservationVariableSynonym;
  };