/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const ObservationUnit = sequelize.define('ObservationUnit', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(100),
    studyId: DataTypes.INTEGER(11),
    level: DataTypes.STRING(254),
    levels: DataTypes.STRING(254),
    blockNumber: DataTypes.STRING(11),
    entryNumber: DataTypes.STRING(11),
    entryType: DataTypes.STRING(50),
    x: DataTypes.STRING(10),
    y: DataTypes.STRING(10),
    sampleId: DataTypes.INTEGER(11),
    germplasmId: DataTypes.INTEGER(11),
    plantingDate: DataTypes.DATE,
    harvestingDate: DataTypes.DATE,
    replicate: DataTypes.STRING(11),
    plantNumber: DataTypes.STRING(11),
    plotNumber: DataTypes.STRING(11),
    containedIn: DataTypes.INTEGER(11),
    locationId: DataTypes.INTEGER(11),
  }, {
      tableName: 'ObservationUnit',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          ObservationUnit.belongsTo(models.Treatment, {
            foreignKey: 'id',              //on ObservationUnit
            targetKey: 'observationUnitId',  //foreign key  
          });
          ObservationUnit.belongsTo(models.Observation, {
            foreignKey: 'id',              //on ObservationUnit
            targetKey: 'observationUnitId',  //foreign key  
          });
          ObservationUnit.belongsTo(models.ObservationUnitXRef, {
            foreignKey: 'id',              //on ObservationUnit
            targetKey: 'observationUnitId',  //foreign key  
          });
          ObservationUnit.belongsTo(models.Treatment, {
            foreignKey: 'id',              //on ObservationUnit
            targetKey: 'observationUnitId',  //foreign key  
          });
          ObservationUnit.belongsTo(models.Study,{
            foreignKey: 'studyId', //on ObsUnit
            targetKey: 'id'
          });
          ObservationUnit.belongsTo(models.Germplasm,{
            foreignKey: 'germplasmId', //on ObsUnit
            targetKey: 'id'
          });          
        }
      },
    });

    return ObservationUnit;
  };