/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Observation = sequelize.define('Observation', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    observationVariableId: DataTypes.INTEGER(11),
    observationUnitId: DataTypes.INTEGER(11),
    operator: DataTypes.INTEGER(11),
    uploadedBy: DataTypes.INTEGER(11),
    observationTimeStamp: DataTypes.DATE,
    value: DataTypes.STRING(50),
  }, {
      tableName: 'Observation',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return Observation;
  };