/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const PersonUploader = sequelize.define('PersonUploader', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(100),
    honorific: DataTypes.STRING(5),
    role: DataTypes.STRING(50),
    email: DataTypes.STRING(50),
    orcid: DataTypes.STRING(50),
    affiliation: DataTypes.INTEGER(11),
  }, {
      tableName: 'Person',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          PersonUploader.belongsTo(models.Observation, {
            foreignKey: 'id',              //on PersonUploader
            targetKey: 'operator',  //foreign key  
          });
          PersonUploader.belongsTo(models.Observation, {
            foreignKey: 'id',              //on PersonUploader
            targetKey: 'uploadedBy',  //foreign key  
          });
          PersonUploader.belongsTo(models.ObservationVariable, {
            foreignKey: 'id',              //on PersonUploader
            targetKey: 'scientist',  //foreign key  
          });
          PersonUploader.belongsTo(models.Institution, {
            foreignKey: 'affiliation',              //on PersonUploader
            targetKey: 'id',  //foreign key  
          });
          PersonUploader.belongsTo(models.Program, {
            foreignKey: 'id',              //on PersonUploader
            targetKey: 'leadPerson',  //foreign key  
          });
          PersonUploader.belongsTo(models.Sample, {
            foreignKey: 'id',              //on PersonUploader
            targetKey: 'takenBy',  //foreign key  
          });
          PersonUploader.belongsTo(models.StudyContact, {
            foreignKey: 'id',              //on PersonUploader
            targetKey: 'contact',  //foreign key  
          }); 
        }
      },
    });

    return PersonUploader;
  };