/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Plot = sequelize.define('Plot', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    locationId: DataTypes.INTEGER(11),
    plotNumber: DataTypes.INTEGER(11),
    blockNumber: DataTypes.INTEGER(11),
    X: DataTypes.INTEGER(11),
    Y: DataTypes.INTEGER(11),
    replicate: DataTypes.INTEGER(11),
    plantingDate: DataTypes.DATE,
    harvestDate: DataTypes.DATE,
  }, {
      tableName: 'Plot',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return Plot;
  };