/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Program = sequelize.define('Program', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    name: DataTypes.STRING(50),
    abbreviation: DataTypes.STRING(10),
    objective: DataTypes.STRING,
    leadPerson: DataTypes.INTEGER(10),
  }, {
    tableName: 'Program',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Program.belongsTo(models.Person, {
          foreignKey: 'leadPerson',              //on Program
          targetKey: 'id',  //foreign key  
        });
        Program.belongsTo(models.Trial, {
          foreignKey: 'id',              //on Program
          targetKey: 'programId',  //foreign key  
        }); 
      }
    },
  });

  return Program;
};
