/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Program = sequelize.define('Program', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(150),
    abbreviation: DataTypes.STRING(100),
    objective: DataTypes.STRING,
    leadPerson: DataTypes.INTEGER(10),
  }, {
      tableName: 'Program',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return Program;
  };