/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const SamplePlant = sequelize.define('SamplePlant', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    sampleId: DataTypes.INTEGER(11),
    plantId: DataTypes.INTEGER(11),
  }, {
      tableName: 'SamplePlant',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {
          SamplePlant.belongsTo(models.Plant, {
            foreignKey: 'plantId',              //on SamplePlant
            targetKey: 'id',  //foreign key  
          });     
          SamplePlant.belongsTo(models.Sample, {
            foreignKey: 'sampleId',              //on SamplePlant
            targetKey: 'id',  //foreign key  
          });     
        }
      },
    });

    return SamplePlant;
  };