/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const ScaleCategory = sequelize.define('ScaleCategory', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    scaleId: DataTypes.INTEGER(11),
    value: DataTypes.FLOAT(50),
    category: DataTypes.STRING(20),
  }, {
    tableName: 'ScaleCategory',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {   
          ScaleCategory.belongsTo(models.Scale, {
          foreignKey: 'scaleId',              //on ScaleCategory
          targetKey: 'id',  //foreign key  
        });  
      }
    },
  });

  return ScaleCategory;
};
