/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const ScaleCategory = sequelize.define('ScaleCategory', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    scaleId: DataTypes.INTEGER(15),
    value: DataTypes.FLOAT,
    category: DataTypes.STRING(50),
  }, {
      tableName: 'ScaleCategory',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          ScaleCategory.belongsTo(models.Scale, {
            foreignKey: 'scaleId',              //on ScaleCategory
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return ScaleCategory;
  };