/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Scale = sequelize.define('Scale', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    scaleId: DataTypes.STRING(40),
    name: DataTypes.STRING(50),
    dataTypeId: DataTypes.INTEGER(11),
    decimalPlaces: DataTypes.INTEGER(11),
    xref: DataTypes.STRING(50),
    min: DataTypes.FLOAT,
    max: DataTypes.FLOAT,
  }, {
      tableName: 'Scale',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
          Scale.belongsTo(models.DataType, {
            foreignKey: 'dataTypeId',  //on this table
            targetKey: 'id'
          });  
          Scale.belongsTo(models.ScaleCategory, {
            foreignKey: 'id',  //on this table
            targetKey: 'scaleId'
          });  
        }
      },
    });

    return Scale;
  };