/**
   * Created by Bruno Costa 24-05-2019
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Search = sequelize.define('Search', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
      germplasmDbIds:{
        type: DataTypes.JSON,
        allowNull: true
      },
      locationDbIds:{
        type: DataTypes.JSON,
        allowNull: true
      },
      observationLevel: DataTypes.STRING(254), 
      observationTimeStampRangeStart: DataTypes.DATE,  
      observationTimeStampRangeEnd: DataTypes.DATE,
      observationVariableDbIds:{
        type: DataTypes.JSON,
        allowNull: true
      },
      programDbIDs:{
        type: DataTypes.JSON,
        allowNull: true
      },
      seasonDbIds:{
        type: DataTypes.JSON,
        allowNull: true
      },
      studyDbIds:{
        type: DataTypes.JSON,
        allowNull: true
      },
      trialDbIds:{
        type: DataTypes.JSON,
       allowNull: true
      },
  }, {
      tableName: 'Search',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });
    return Search;
  };