/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Species = sequelize.define('Species', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    cropId: DataTypes.INTEGER(11),
    genus: DataTypes.STRING(50),
    species: DataTypes.STRING(50),
    speciesAuthority: DataTypes.STRING(50),
    subtaxa: DataTypes.STRING(50),
    subtaxaAuthority: DataTypes.STRING(50),
    NCBItaxonId: DataTypes.INTEGER(11),
  }, {
      tableName: 'Species',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return Species;
  };