/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const StudyTreatment = sequelize.define('StudyTreatment', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    plotId: DataTypes.INTEGER(11),
    treatmentModalityId: DataTypes.INTEGER(11),
  }, {
      tableName: 'StudyTreatment',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return StudyTreatment;
  };