/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const StudyAdditionalInfo = sequelize.define('StudyAdditionalInfo', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    studyId: DataTypes.INTEGER(11),
    propertyName: DataTypes.STRING(50),
    propertyValue: DataTypes.STRING(100),
  }, {
      tableName: 'StudyAdditionalInfo',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          StudyAdditionalInfo.belongsTo(models.Study, {
            foreignKey: 'studyId',              //on StudyAdditionalInfo
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return StudyAdditionalInfo;
  };