/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const StudyObservationVariable = sequelize.define('StudyObservationVariable', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    studyId: DataTypes.INTEGER(11),
    observationVariableId: DataTypes.INTEGER(11),
  }, {
      tableName: 'StudyObservationVariable',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return StudyObservationVariable;
  };