/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const StudyContact = sequelize.define('StudyContact', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    studyId: DataTypes.INTEGER(11),
    contact: DataTypes.INTEGER(11),
  }, {
      tableName: 'StudyContact',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          StudyContact.belongsTo(models.Study, {
            foreignKey: 'studyId',              //on StudyContact
            targetKey: 'id',  //foreign key  
          });
          StudyContact.belongsTo(models.Person, {
            foreignKey: 'contact',              //on StudyContact
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return StudyContact;
  };