/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const StudyType = sequelize.define('StudyType', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    name: DataTypes.STRING(100),
    description: DataTypes.STRING,
  }, {
    tableName: 'StudyType',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
/*        StudyType.belongsTo(models.ContextOfUse, {
          foreignKey: 'id',              //on StudyType
          targetKey: 'studyTypeId',  //foreign key  
        });*/
        StudyType.belongsTo(models.Study, {
          foreignKey: 'id',              //on StudyType
          targetKey: 'type',  //foreign key  
        }); 
      }
    },
  });

  return StudyType;
};
