/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Trait = sequelize.define('Trait', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    traitId: DataTypes.STRING(100),
    name: DataTypes.STRING(100),
    class: DataTypes.STRING(50),
    description: DataTypes.STRING,
    mainAbbreviation: DataTypes.STRING(5),
    entity: DataTypes.STRING(50),
    attribute: DataTypes.STRING(50),
    status: DataTypes.STRING(20),
    xref: DataTypes.STRING(50),
  }, {
    tableName: 'Trait',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Trait.belongsTo(models.ObservationVariable, {
          foreignKey: 'id',              //on Trait
          targetKey: 'traitId',  //foreign key  
        });
        Trait.belongsTo(models.TraitAlternativeAbbreviation, {
          foreignKey: 'id',              //on Trait
          targetKey: 'traitId',  //foreign key  
        });
        Trait.belongsTo(models.TraitSynonym, {
          foreignKey: 'id',              //on Trait
          targetKey: 'traitId',  //foreign key  
        }); 
      }
    },
  });

  return Trait;
};
