/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const TraitSynonym = sequelize.define('TraitSynonym', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    traitId: DataTypes.INTEGER(15),
    synonym: DataTypes.STRING(100),
  }, {
      tableName: 'TraitSynonym',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
          TraitSynonym.belongsTo(models.Trait, {
            foreignKey: 'traitId',              //on TraitSynonym
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return TraitSynonym;
  };