/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const TreatmentModality = sequelize.define('TreatmentModality', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    treatmentFactorId: DataTypes.INTEGER(11),
    modality: DataTypes.STRING(175),
  }, {
      tableName: 'TreatmentModality',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return TreatmentModality;
  };