/**
 * Created by Bruno Costa 02-02-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const TreatmentModality = sequelize.define('TreatmentModality', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    treatmentFactorId: DataTypes.INTEGER(11),
    modality: DataTypes.STRING(100),
  }, {
    tableName: 'TreatmentModality',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        TreatmentModality.belongsTo(models.StudyTreatment, {
          foreignKey: 'id',              //on TreatmentModality
          targetKey: 'treatmentModalityId',  //foreign key  
        });
        TreatmentModality.belongsTo(models.TreatmentFactor, {
          foreignKey: 'treatmentFactorId',              //on TreatmentModality
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return TreatmentModality;
};
