/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Treatment = sequelize.define('Treatment', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    observationUnitId: DataTypes.INTEGER(11),
    treatmentModalityId: DataTypes.INTEGER(11),
  }, {
      tableName: 'Treatment',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Treatment.belongsTo(models.TreatmentModality, {
            foreignKey: 'treatmentModalityId',              //on Treatment
            targetKey: 'id',  //foreign key  
          });
          Treatment.belongsTo(models.ObservationUnit, {
            foreignKey: 'observationUnitId',              //on Treatment
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Treatment;
  };