/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const TreatmentFactor = sequelize.define('TreatmentFactor', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    factor: DataTypes.STRING(50),
  }, {
      tableName: 'TreatmentFactor',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          TreatmentFactor.belongsTo(models.TreatmentModality, {
            foreignKey: 'id',              //on TreatmentFactor
            targetKey: 'treatmentFactorId',  //foreign key  
          }); 
        }
      },
    });

    return TreatmentFactor;
  };