/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const TrialAuthorship = sequelize.define('TrialAuthorship', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    trialId: DataTypes.INTEGER(11),
    authorshipId: DataTypes.INTEGER(11),
  }, {
      tableName: 'TrialAuthorship',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          TrialAuthorship.belongsTo(models.Trial, {
            foreignKey: 'trialId',              //on TrialAuthorship
            targetKey: 'id',  //foreign key  
          });
          TrialAuthorship.belongsTo(models.Authorship, {
            foreignKey: 'authorshipId',              //on TrialAuthorship
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return TrialAuthorship;
  };