/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const TrialAdditionalInfo = sequelize.define('TrialAdditionalInfo', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    trialId: DataTypes.INTEGER(11),
    propertyName: DataTypes.STRING(50),
    propertyValue: DataTypes.STRING(200),
  }, {
      tableName: 'TrialAdditionalInfo',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return TrialAdditionalInfo;
  };