/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Versions = sequelize.define('Versions', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    callId: DataTypes.INTEGER(11),
    version: DataTypes.STRING(5),
  }, {
      tableName: 'Versions',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
          Versions.belongsTo(models.Calls, {
            foreignKey: 'callId',              //on Calls
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Versions;
  };